services:
  schooldashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-dashboard
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
