services:
  schooldashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-dashboard
    restart: unless-stopped
    ports:
      # Modifiez le port hôte (ex: 8090, 8888, 3000...) si le port est déjà occupé
      - "${PORT:-8090}:80"
    environment:
      - NODE_ENV=production
